Adding single container support

diff --git a/cft_sidecar.yaml b/cft_sidecar.yaml
--- a/cft_sidecar.yaml
+++ b/cft_sidecar.yaml
@@ -36,6 +36,7 @@ Metadata:
       - SidecarCACertificateRoleArn
       - SidecarTLSCertificateSecretArn
       - SidecarCACertificateSecretArn
+      - UseSingleContainer
     - Label:
         default: 'High Availability'
       Parameters:
@@ -221,6 +222,14 @@ Parameters:
   NamePrefix:
     Type: String
     Description: "Prefix for names of the AWS resources created. Maximum length is 24 characters."
+
+  UseSingleContainer:
+    Description: "Use single container for sidecar deployment"
+    Type: "String"
+    Default: "false"
+    AllowedValues:
+      - "true"
+      - "false"
 
 Conditions:
   useCustomTag: !Not [!Equals [!Ref CustomTag, '']]
@@ -663,8 +672,17 @@ Resources:
                 function launch () {
                     echo "Starting sidecar..."
                     cd /home/ec2-user
-                    retry docker compose -f sidecar.compose.yaml pull -q
-                    retry docker compose -f sidecar.compose.yaml up -d
+                    if [[ ${UseSingleContainer} == "true" ]]; then
+                      SINGLE_CONTAINER_IMAGE=${ContainerRegistry}/cyral-sidecar:$SIDECAR_VERSION
+                      retry docker pull -q $SINGLE_CONTAINER_IMAGE
+                      retry docker run -d --name sidecar --network=host --log-driver=local --log-opt max-size=500m --restart=unless-stopped --env-file .env $SINGLE_CONTAINER_IMAGE
+                      if ! containerCheck "sidecar"; then
+                        echo "--> Problem with sidecar! Inspect the logs to diagnose the issue. <--"
+                      fi
+                    else
+                      retry docker compose -f sidecar.compose.yaml pull -q
+                      retry docker compose -f sidecar.compose.yaml up -d
+                    fi
                 }
               - sidecar_tls_certificate_secret_arn: !If [sidecarTLSCertificateSecretArnNotEmpty, !Ref SidecarTLSCertificateSecretArn, '']
                 sidecar_ca_certificate_secret_arn: !If [sidecarCACertificateSecretArnNotEmpty, !Ref SidecarCACertificateSecretArn, '']
@@ -738,12 +756,20 @@ Resources:
                 echo "Sidecar version: $SIDECAR_VERSION"
 
                 docker_setup
-                docker_compose_install
+                if [[ ${UseSingleContainer} == "true" ]]; then
+                  echo "Skipping Docker Compose Install, not required for single container"
+                else
+                  docker_compose_install
+                fi
                 update_nginx_resolver
                 load_certs
                 load_idp_certs
                 registry_login
-                retry download_sidecar
+                if [[ ${UseSingleContainer} == "true" ]]; then
+                  echo "Skipping Download Sidecar Compose File, not required for single container"
+                else
+                  retry download_sidecar
+                fi
 
                 # Initializing environment variables
                 env_var=$(cat <<EOF
